/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KhoanThuView;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import view.KhoanThuView;
import KhoanThuController.ThemKhoanThuController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.KhoanThu;
import service.ExcelReader;

/**
 *
 * @author MY PC
 */
public class ThemKhoanThu extends javax.swing.JFrame {

    /**
     * Creates new form ThemKhoanThu
     */
    
    String option = new String();
    private ThemKhoanThuController addKT;
    ExcelReader serice;
    
    public ThemKhoanThu() {
        initComponents();
        addKT  = new ThemKhoanThuController(this);
         this.setLocationRelativeTo(null);
         serice = new ExcelReader();
         this.LoaiKhoanThu.setEnabled(true);
         this.DichVu.setEnabled(true);
         
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
         
         
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TenKhoanThu = new javax.swing.JTextField();
        TrangThai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        LoaiKhoanThu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        DonGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CongTy = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DichVu = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        XeMay = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Oto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ngayBDText = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khoản thu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Tên khoản thu");

        jLabel2.setText("Loại khoản thu");

        jLabel3.setText("Ngày bắt đầu:");

        jLabel6.setText("Trạng thái");

        TenKhoanThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenKhoanThuActionPerformed(evt);
            }
        });

        TrangThai.setEditable(false);
        TrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrangThaiActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("ID: ");

        LoaiKhoanThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phí dịch vụ", "Phí quản lý", "Phí đóng góp", "Phí gửi xe", "Phí thu hộ" }));
        LoaiKhoanThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiKhoanThuActionPerformed(evt);
            }
        });

        jLabel7.setText("Đơn giá:");

        DonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonGiaActionPerformed(evt);
            }
        });

        jLabel8.setText("( đơn vị: nghìn Đồng/m2 )");

        jLabel9.setText("Tên công ty  cấp");

        CongTy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CongTyActionPerformed(evt);
            }
        });

        jLabel10.setText("Tên dịch vụ:");

        DichVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điện", "Nước", "Internet" }));

        jLabel11.setText("Giá xe máy: ");

        XeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XeMayActionPerformed(evt);
            }
        });

        jLabel13.setText("Giá ô tô: ");

        Oto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtoActionPerformed(evt);
            }
        });

        jLabel14.setText("( đơn vị: nghìn Đồng/xe)");

        jButton6.setText("Next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText("(*)");

        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("(*)");

        jLabel29.setForeground(new java.awt.Color(255, 0, 51));
        jLabel29.setText("(*)");

        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("(*)");

        ngayBDText.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TenKhoanThu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 84, Short.MAX_VALUE)
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TrangThai)
                                    .addComponent(LoaiKhoanThu, 0, 267, Short.MAX_VALUE)
                                    .addComponent(DonGia)
                                    .addComponent(CongTy)
                                    .addComponent(DichVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(XeMay, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ngayBDText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(173, 173, 173)
                                                .addComponent(jLabel30))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel27))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Oto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TenKhoanThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LoaiKhoanThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel27))
                    .addComponent(ngayBDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(XeMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(Oto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CongTy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        KhoanThuView viewMain = new KhoanThuView();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date ngayBatDau;
    try{
        String ngay = dateFormat.format(this.ngayBDText.getDate());
        ngayBatDau = dateFormat.parse(ngay);
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Sai định dạng ngày");  
        return;
    }
        
        if(this.TenKhoanThu.getText().equals("") || this.idText.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin phí !");
              return; 
         }else{
             if( (this.LoaiKhoanThu.getSelectedItem().equals("Phí dịch vụ") || this.LoaiKhoanThu.getSelectedItem().equals("Phí quản lý")) && this.DonGia.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin khoản thu !");
                 return; 
             }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí gửi xe") && (this.Oto.getText().equals("") ||this.XeMay.getText().equals(""))){
                 JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin phí gửi xe!");
                 return; 
             }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí thu hộ") && (this.CongTy.getText().equals(""))){
                 JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin phí thu hộ!");
                 return; 
             }
                        
         }
        
        
        String id = this.idText.getText();
        String tenKhoanThu = this.TenKhoanThu.getText();
        String loaiKhoanThu = this.LoaiKhoanThu.getSelectedItem()+"";
        

    
    String trangThai = "Chưa hoàn thành";
    
    
    KhoanThu khoanthu = new KhoanThu();
    
    khoanthu.setIdKhoanThu(id);
    khoanthu.setTenKhoanThu(tenKhoanThu);
    khoanthu.setLoaiKhoanThu(loaiKhoanThu);
    khoanthu.setNgayBatDau(ngayBatDau);
    khoanthu.setTrangThai(trangThai);
    
    
        if(this.addKT.addKhoanThu(khoanthu)){
        
        if(this.LoaiKhoanThu.getSelectedItem().equals("Phí dịch vụ")){
            int donGia = Integer.parseInt(this.DonGia.getText());
            khoanthu.setDonGia(donGia);
            this.addKT.addPhiBatBuoc(khoanthu);
            
            
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí quản lý")){
            int donGia = Integer.parseInt(this.DonGia.getText());
            khoanthu.setDonGia(donGia);
            this.addKT.addPhiBatBuoc(khoanthu);
            
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí đóng góp")){
            khoanthu.setTongThu(0);
            this.addKT.addPhiDongGop(khoanthu);
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí gửi xe")){
            int giaXeMay = Integer.parseInt(this.XeMay.getText());
            int giaOto = Integer.parseInt(this.Oto.getText());
            khoanthu.setXemay(giaXeMay);
            khoanthu.setOto(giaOto);
            this.addKT.addPhiGuiXe(khoanthu);
            
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí thu hộ")){
            String tenCongTy = this.CongTy.getText();
            String dichVu = this.DichVu.getSelectedItem()+"";
            khoanthu.setTenCongTy(tenCongTy);
            khoanthu.setDichVu(dichVu);
            this.addKT.addPhiThuHo(khoanthu);
        }
        this.addKT.themDanhSachHoDong(khoanthu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrangThaiActionPerformed

    private void TenKhoanThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenKhoanThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenKhoanThuActionPerformed

    private void DonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonGiaActionPerformed

    private void CongTyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CongTyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CongTyActionPerformed

    private void XeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XeMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XeMayActionPerformed

    private void OtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.LoaiKhoanThu.getSelectedItem().equals("Phí dịch vụ") || this.LoaiKhoanThu.getSelectedItem().equals("Phí quản lý")){
         this.DonGia.setVisible(true);
         this.jLabel7.setVisible(true);
         this.jLabel8.setVisible(true);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
         
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí gửi xe")){
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(true);
         this.jLabel11.setVisible(true);
         this.XeMay.setVisible(true);
         this.jLabel13.setVisible(true);
         this.jLabel14.setVisible(true);
        }if(this.LoaiKhoanThu.getSelectedItem().equals("Phí thu hộ")){
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(true);
         this.jLabel9.setVisible(true);
         this.DichVu.setVisible(true);
         this.jLabel10.setVisible(true);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí đóng góp")){
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void LoaiKhoanThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiKhoanThuActionPerformed

    }//GEN-LAST:event_LoaiKhoanThuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CongTy;
    private javax.swing.JComboBox<String> DichVu;
    private javax.swing.JTextField DonGia;
    private javax.swing.JComboBox<String> LoaiKhoanThu;
    private javax.swing.JTextField Oto;
    private javax.swing.JTextField TenKhoanThu;
    private javax.swing.JTextField TrangThai;
    private javax.swing.JTextField XeMay;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JDateChooser ngayBDText;
    // End of variables declaration//GEN-END:variables
}
